export { toLosslessJson, type JsonValue } from './lossless.ts';
export type {
  QaAction,
  QaActionReceipt,
  QaApprovalGate,
  QaApprovalOutcome,
  QaComputerAppIdentity,
  QaComputerEvidence,
  QaComputerHelperStatus,
  QaComputerWindowIdentity,
  QaDriverAdapter,
  QaEvidence,
  QaEvidenceOptions,
  QaObservation,
  QaObserveOptions,
  QaPageRef,
  QaReceiptStatus,
  QaSemanticNode,
  QaSessionInfo,
  QaSettleReport,
  QaStartOptions,
  QaStopResult,
  QaVisualCapture,
  QaVisualCaptureInfo,
  QaVisualObserveOptions,
} from './adapter.ts';
export { toVisualCaptureInfo } from './adapter.ts';
export {
  captureLatestVisual,
  QaSession,
  QaSessionManager,
  type QaActOutcome,
  type QaActResult,
  type QaLatestVisual,
  type QaSessionOptions,
} from './session.ts';
export {
  normalizeObservableValue,
  observeUntilStable,
  projectSemanticView,
  resolveSettlePolicy,
  QA_SETTLE_BUDGET_MS,
  QA_SETTLE_INTERVAL_MS,
  QA_SETTLE_POST_CHANGE_QUIET_MS,
  QA_SETTLE_QUIET_MS,
  type QaEchoMask,
  type QaSettleCallOptions,
  type QaSettlePolicy,
  type QaSettleResult,
} from './settle.ts';
